Repository ossf/tac, pull requests merged in 2023-11, with the labels that each got.

#205 Accommodate spec development in a Project
  process/project-lifecycle.md
Labels: documentation, enhancement, administration

#212 Update WG Lifecycle
  process/working-group-lifecycle.md
Labels: documentation, enhancement, administration

#221 too many columns and notes link
  .github/actions/spelling/allow.txt
  README.md
Labels: documentation, administration

#219 Update Process README.md
  process/README.md
  process/TI-lifecycle-stages.png
Labels: OpsModel

#220 Add TAC Member R&Rs
  process/tac-member-R&Rs.md
Labels: OpsModel
