Repository ossf/tac, pull requests merged in 2024-11, with the labels that each got.

#399 Update tac-member-R&Rs.md
  process/tac-member-R&Rs.md
Labels: documentation, Editorial

#408 Update README Working Groups, Projects and SIGs lists and links
  README.md
Labels: Non-spec

#375 Add AI/ML WG to the lifecycle documents.
  README.md
  process/wg-lifecycle-documents/ai_ml_incubating_stage.md
Labels: documentation, TI Lifecycle

#409 Add 2025 TAC Election nominations
  elections/OpenSSF-TAC-Nomiations-2025.md
Labels: ElectionProcess

#398 Add security baseline reqs to project lifecycle templates
  CHANGELOG.md
  process/templates/PROJECT_NAME_graduation_stage.md
  process/templates/PROJECT_NAME_incubation_stage.md
Labels: administration, Editorial
