Repository ossf/tac, pull requests merged in 2024-08, with the labels that each got.

#372 Update the GUAC entry to point to the website
  README.md
Labels: Non-spec, Fix

#373 Clarifications on Logo entitlement vs. Badge usage
  CHANGELOG.md
  process/TI-Gives+Gets.md
Labels: documentation, Content

#367 bomctl - OpenSSF Sandbox Application
  README.md
  process/project-lifecycle-documents/bomctl_sandbox_stage.md
Labels: TI Lifecycle

#359 Create 2024-Q3-BEST-WG.md
  TI-reports/2024/2024-Q3-BEST-WG.md
Labels: documentation, TI Lifecycle, Content

#374 Label Security Metric project as archived in README
  CHANGELOG.md
  README.md
Labels: administration, Content

#376 [security_baseline.md] Alter "or" to "to" to denote a range
  process/security_baseline.md
Labels: documentation, Fix

#347 Add model signing as a sandbox project
  README.md
  process/project-lifecycle-documents/model_signing_sandbox_stage.md
Labels: Major
