Repository ossf/tac, pull requests merged in 2024-05, with the labels that each got.

#319 Create TAC-Decision-Process.md
  process/TAC-Decision-Process.md
Labels: documentation, administration

#327 Add infrastructure for TI reports to be submitted via github PR
  CHANGELOG.md
  README.md
  TI-reports/0000-quarterly-update-template.md
  TI-reports/README.md
Labels: enhancement, administration, Content

#334 Improve election process and timeline
  CHANGELOG.md
  elections/tac-and-scir-election-process.md
Labels: ElectionProcess, Content

#332 Add RSTUF as incubating project
  .github/actions/spelling/allow.txt
  README.md
  process/project-lifecycle-documents/repository_service_for_tuf_incubation_stage.md
Labels: administration, TI Lifecycle

#338 Document Q2 2024 TI funding cycle
  process/TI Funding Request Process.md
Labels: administration, Editorial
