Repository ossf/tac, pull requests merged in 2024-09, with the labels that each got.

#377 Add AI/ML WG & model signing Q3 report as PR
  TI-reports/2024/2024-Q3-AI-ML-WG.md
Labels: documentation, TI Lifecycle

#382 Add protection in use
  process/security_baseline.md
Labels: documentation, Content

#385 Add .gitvote file to activate GH voting on the TAC repo for TI funding request
  .gitvote.yml
Labels: ElectionProcess, vote

#381 Update tac-member-R&Rs.md
  process/tac-member-R&Rs.md
Labels: administration, Content
