Repository ossf/tac, pull requests merged in 2025-01, with the labels that each got.

#433 Update terms of 2024 community-elected TAC members
  README.md
Labels: Fix

#407 Create 2024-Q4-VULN-WG.md
  TI-reports/2024/2024-Q4-VULN-WG.md
Labels: For Review, TI Update

#437 2025 Q1 Securing Critical Projects WG update
  TI-reports/2025/2025-Q1-SCP-WG.md
Labels: TI Update

#432 Simplify docs around Chair election, roles, and responsibilities
  CHANGELOG.md
  elections/tac-and-scir-election-process.md
  process/TAC-Decision-Process.md
  process/tac-member-R&Rs.md
Labels: Content

#416 Create approved_project_onboarding.yml
  .github/ISSUE_TEMPLATE/approved_project_onboarding.yml
Labels: documentation

#439 Add AI/ML WG Q1 updates to the TAC
  TI-reports/2025/2025-Q1-AI-ML-WG.md
Labels: TI Update
